name: cicd
on: 
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
jobs:
  static-checks:
    uses: ./.github/workflows/_static-checks.yml
  unit-tests:
    uses: ./.github/workflows/_unit-tests.yml
  build-package:
    uses: ./.github/workflows/_build-package.yml
  upload-package:
    if: startsWith(github.ref, 'refs/tags/') 
    uses: ./.github/workflows/_upload-package.yml
    needs: [build-package, unit-tests, static-checks]
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
